"""initial schema

Revision ID: 47dd7978efe3
Revises: 
Create Date: 2026-10-09 08:46:46.275442

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '47dd7978efe3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='supplierstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_code'), ['code'], unique=True)

    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.Enum('int', 'float', 'enum', name='settingvaluetype', native_enum=False, length=16), nullable=False),
    sa.Column('category', sa.Enum('stock_alert', 'replenishment', 'qc', 'caliber', name='settingcategory', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('setting_id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('electronics', 'bags', 'home', 'apparel', 'beauty', 'toys', name='productcategory', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('developing', 'on_sale', 'discontinued', name='productstatus', native_enum=False, length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('default_supplier_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_default_supplier_id'), ['default_supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku_code'), ['sku_code'], unique=True)

    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ordered', 'partial_received', 'received', 'closed', 'cancelled', name='postatus', native_enum=False, length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_no'), ['po_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('daily_sales',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('sales_id'),
    sa.UniqueConstraint('product_id', 'date', name='uq_sales_product_date')
    )
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sales_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_sales_product_id'), ['product_id'], unique=False)

    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_available', sa.Integer(), nullable=False),
    sa.Column('qty_pending', sa.Integer(), nullable=False),
    sa.Column('qty_defective', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_product_id'), ['product_id'], unique=True)

    op.create_table('inventory_transactions',
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('stock_type', sa.Enum('available', 'pending', 'defective', name='stocktype', native_enum=False, length=16), nullable=False),
    sa.Column('txn_type', sa.Enum('recv_inbound', 'qc_pass', 'qc_fail', 'manual_adjust', 'adjust_outbound', name='txntype', native_enum=False, length=32), nullable=False),
    sa.Column('ref_doc_type', sa.String(length=16), nullable=False),
    sa.Column('ref_doc_no', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_ref_doc_no'), ['ref_doc_no'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('receiving_orders',
    sa.Column('recv_id', sa.Integer(), nullable=False),
    sa.Column('recv_no', sa.String(length=32), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_inspection', 'inspecting', 'completed', name='receivingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.PrimaryKeyConstraint('recv_id')
    )
    with op.batch_alter_table('receiving_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receiving_orders_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receiving_orders_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_receiving_orders_recv_no'), ['recv_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_receiving_orders_status'), ['status'], unique=False)

    op.create_table('replenishment_suggestions',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('qty_in_transit', sa.Integer(), nullable=False),
    sa.Column('forecast_7d', sa.Integer(), nullable=False),
    sa.Column('suggested_qty', sa.Integer(), nullable=False),
    sa.Column('days_cover', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Enum('normal', 'suggest', 'emergency', name='urgency', native_enum=False, length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    with op.batch_alter_table('replenishment_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replenishment_suggestions_product_id'), ['product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_replenishment_suggestions_urgency'), ['urgency'], unique=False)

    op.create_table('inspection_orders',
    sa.Column('insp_id', sa.Integer(), nullable=False),
    sa.Column('insp_no', sa.String(length=32), nullable=False),
    sa.Column('recv_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_inspection', 'inspecting', 'completed', name='inspectionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.Column('inspector', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recv_id'], ['receiving_orders.recv_id'], ),
    sa.PrimaryKeyConstraint('insp_id')
    )
    with op.batch_alter_table('inspection_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_orders_insp_no'), ['insp_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_orders_recv_id'), ['recv_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_orders_status'), ['status'], unique=False)

    op.create_table('receiving_items',
    sa.Column('recv_item_id', sa.Integer(), nullable=False),
    sa.Column('recv_id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.item_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['recv_id'], ['receiving_orders.recv_id'], ),
    sa.PrimaryKeyConstraint('recv_item_id')
    )
    with op.batch_alter_table('receiving_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receiving_items_po_item_id'), ['po_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receiving_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receiving_items_recv_id'), ['recv_id'], unique=False)

    op.create_table('inspection_items',
    sa.Column('insp_item_id', sa.Integer(), nullable=False),
    sa.Column('insp_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_inspected', sa.Integer(), nullable=False),
    sa.Column('qty_passed', sa.Integer(), nullable=False),
    sa.Column('qty_failed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insp_id'], ['inspection_orders.insp_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('insp_item_id')
    )
    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_items_insp_id'), ['insp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_items_product_id'), ['product_id'], unique=False)

    op.create_table('defect_records',
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('insp_item_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.Enum('scratch', 'functional', 'packaging', 'dimension', 'label', 'other', name='defectreason', native_enum=False, length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insp_item_id'], ['inspection_items.insp_item_id'], ),
    sa.PrimaryKeyConstraint('defect_id')
    )
    with op.batch_alter_table('defect_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_records_insp_item_id'), ['insp_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_records_reason_code'), ['reason_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_records_reason_code'))
        batch_op.drop_index(batch_op.f('ix_defect_records_insp_item_id'))

    op.drop_table('defect_records')
    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_items_insp_id'))

    op.drop_table('inspection_items')
    with op.batch_alter_table('receiving_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receiving_items_recv_id'))
        batch_op.drop_index(batch_op.f('ix_receiving_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_receiving_items_po_item_id'))

    op.drop_table('receiving_items')
    with op.batch_alter_table('inspection_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_orders_status'))
        batch_op.drop_index(batch_op.f('ix_inspection_orders_recv_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_orders_insp_no'))

    op.drop_table('inspection_orders')
    with op.batch_alter_table('replenishment_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replenishment_suggestions_urgency'))
        batch_op.drop_index(batch_op.f('ix_replenishment_suggestions_product_id'))

    op.drop_table('replenishment_suggestions')
    with op.batch_alter_table('receiving_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receiving_orders_status'))
        batch_op.drop_index(batch_op.f('ix_receiving_orders_recv_no'))
        batch_op.drop_index(batch_op.f('ix_receiving_orders_received_at'))
        batch_op.drop_index(batch_op.f('ix_receiving_orders_po_id'))

    op.drop_table('receiving_orders')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_po_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_ref_doc_no'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_created_at'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_product_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sales_product_id'))
        batch_op.drop_index(batch_op.f('ix_daily_sales_date'))

    op.drop_table('daily_sales')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_no'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku_code'))
        batch_op.drop_index(batch_op.f('ix_products_default_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_category'))

    op.drop_table('system_settings')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_code'))

    op.drop_table('suppliers')
    # ### end Alembic commands ###
